# Generated by Django 5.2.10 on 2026-01-28 10:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('listing_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='builds/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('sold', 'Продан'), ('cancelled', 'Отменён')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('mb', 'Motherboard'), ('ram', 'RAM'), ('ssd', 'SSD'), ('hdd', 'HDD'), ('psu', 'PSU'), ('case', 'Case'), ('cooler', 'Cooler'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('in_stock', 'На складе'), ('reserved', 'Зарезервирован'), ('installed', 'В сборке'), ('sold', 'Продан'), ('written_off', 'Списан')], default='in_stock', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_items', to='tracker.build')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_links', to='tracker.inventoryitem')),
            ],
            options={
                'unique_together': {('build', 'item')},
            },
        ),
        migrations.AddField(
            model_name='build',
            name='items',
            field=models.ManyToManyField(related_name='builds', through='tracker.BuildItem', to='tracker.inventoryitem'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('build', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='tracker.build')),
            ],
        ),
    ]
