# Generated by Django 6.0.1 on 2026-01-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('gaming', 'Игровая'), ('office', 'Офисная'), ('workstation', 'Рабочая станция')], default='gaming', max_length=20, verbose_name='Тип сборки')),
                ('description', models.TextField(blank=True, null=True)),
                ('listing_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='builds/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Выставлен на продажу'), ('sold', 'Продан')], default='draft', max_length=20)),
                ('work_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Затрачено часов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchased_at', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cpu', 'Процессор'), ('gpu', 'Видеокарта'), ('motherboard', 'Материнская плата'), ('ram', 'Оперативная память'), ('ssd', 'SSD накопитель'), ('hdd', 'Жесткий диск'), ('psu', 'Блок питания'), ('case', 'Корпус'), ('cooler', 'Охлаждение'), ('other', 'Прочее')], default='other', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('in_stock', 'На складе'), ('installed', 'В сборке'), ('sold', 'Продан'), ('written_off', 'Списан')], default='in_stock', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_bought', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_used', models.PositiveIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_materials', to='tracker.build')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.consumable')),
            ],
        ),
        migrations.CreateModel(
            name='BuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_items', to='tracker.build')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_links', to='tracker.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sold_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('build', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_record', to='tracker.build')),
            ],
        ),
    ]
